# Generated by Django 5.1.6 on 2025-03-30 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="شماره تماس باید به این فرمت باشد: '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تماس'),
        ),
    ]
